// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace DataLabeling.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108000000_AddMissingTables")]
    public partial class AddMissingTables : Migration
    {
    }
}
